name=MyRP_ESP32
version=1.0.0
author=ชัยวัฒน์
maintainer=ชัยวัฒน์
sentence=ไลบรารีหุ่นยนต์แข่งขัน ESP32-S3 (MyRP)
paragraph=รองรับ fline, bline, gyro, servo, PID control สำหรับหุ่นยนต์แข่งขัน บน ESP32-S3
category=Device Control
architectures=esp32
precompiled=full
ldflags=-lMyRP_ESP32