name=MyRP_Pico2
version=1.0.0
author=ชัยวัฒน์
maintainer=ชัยวัฒน์
sentence=ไลบรารีหุ่นยนต์แข่งขันสำหรับ Raspberry Pi Pico (MyRP_Pico2)
paragraph=Static precompiled library สำหรับปกปิดโค้ด - รองรับมอเตอร์, เซนเซอร์ 8 ช่อง, Gyro BMI160, Servo, fline/bline, sw()
category=Robotics
architectures=rp2040
dot_a_linkage=true
includes=MyRP_Pico2.h